### ISSUE TITLE
crashes with circular references

### ISSUE THREAD

**Issue by lselden** [readmeio/api#313]
I'm trying to load an OpenAPI 3.0 doc where there are circular references to components (i.e. `comment` has child array of `comment` objects). It's crashing with "TypeError: Converting circular structure to JSON". 

relevant code: https://github.com/readmeio/api/blob/main/packages/api/src/cache.js#L152

I don't know your code, but maybe you need to [`bundle`](https://apitools.dev/json-schema-ref-parser/docs/ref-parser.html#bundleschema-options-callback) instead of [`dereference`](https://apitools.dev/json-schema-ref-parser/docs/ref-parser.html#bundleschema-options-callback])?

**Comment by erunion** [comment]
Are you comfortable sharing the OpenAPI definition that's causing this?

**Comment by josei** [comment]
`@codat/v1.1.0#1mld74kq6wk0s1` crashes because of circular structures
