### ISSUE TITLE
Preload api at build time in a serverless env

### ISSUE THREAD

**Issue by n-sviridenko** [readmeio/api#363]
Is there any way to preload the cache? In a serverless environment, it'll be populated every time which will slow down the function execution speed.

**Comment by erunion** [comment]
At the moment there isn't but this is something we're planning on tackling early next year.

**Comment by erunion** [comment]
We shipped a new CLI system in the v5 beta that accomplishes this by pre-fetching, installing, and running code generation. You can see docs on this here: https://api.readme.dev/docs/usage#code-generation
