### ISSUE TITLE
Create a code sample generation target for httpsnippet

### ISSUE THREAD

**Issue by erunion** [readmeio/api#39]
Update [httpsnippet](http://npm.im/httpsnippet) to support supplying custom languages and custom targets so we can generate code samples for this library with it.

**Comment by erunion** [comment]
https://www.npmjs.com/package/httpsnippet-client-api

🏄

**Comment by gkoberger** [comment]
![](https://media1.giphy.com/media/31lPv5L3aIvTi/giphy.gif?cid=ecf05e47e09685942df812fb941a3c9a81e6843ffb973bde&rid=giphy.gif)
