### ISSUE TITLE
Error: Cannot find module 'ajv/dist/core'

### ISSUE THREAD

**Issue by DashBarkHuss** [readmeio/api#416]
I'm getting `Error: Cannot find module 'ajv/dist/core'` when trying to require `require('api')`. It's coming from the dependancy `ajv-draft-04@1.0.0`.
```bash
└─┬ api@4.2.0  
  └─┬ @readme/openapi-parser@2.0.3    
    └── ajv-draft-04@1.0.0 
```
              
              
api version 4.2.0

**Comment by erunion** [comment]
I'm having trouble replicating this, what version of Node and NPM are you running?

Using Node v14.18.2 and NPM 7.24.2:

```js
{
  "dependencies": {
    "api": "^4.2.0"
  }
}
```

```js
const api = require('api');

const petstore = api('https://raw.githubusercontent.com/readmeio/oas-examples/main/3.1/json/petstore.json');

(async () => {
  await petstore.getPetById({ petId: 1234 }).then(res => {
    console.log(res)
  }).catch(err => {
    console.error(err);
  })
})();
```

```
$ node index.js
Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      [Symbol(kCapture)]: false,
      [Symbol(kTransformState)]: [Object]
    },
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'https://petstore.swagger.io/v2/pet/1234',
    status: 404,
    statusText: 'Not Found',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 1
  }
}
```

**Comment by DashBarkHuss** [comment]
npm 6.14.10
node v12.6.0

I read it could be related to the version according to this similar [issue](https://issuehunt.io/r/sindresorhus/electron-store/issues/185) but it wasn't 100% clear in that thread. I'm updating node (though it's taking long because it's difficult on the new M1 macs)

**Comment by erunion** [comment]
Updating npm might be enough to fix it, npm@7 has done a better job for me with AJV dependencies in most libraries that use it. Let me know if updating solves it. And for what it's worth we're dropping support for Node 12 in the next major release.

**Comment by erunion** [comment]
Yeah if you don't mind. Sorry :(

**Comment by erunion** [comment]
Also do you have AJV installed anywhere else with your codebase? Could be that a different version of AJV or `ajv-draft-04` are trying to get loaded and they don't have this `dist/core` file.

**Comment by DashBarkHuss** [comment]
Ok I switched to the same versions of node and npm as you.  node v14.18.2 and npm 7.24.2 using nvm. But still had the issue

You were right it was the wrong version of AJV. 

I ran `$ npm ls ajv` and got:

```bash
├─┬ api@4.2.0
│ └─┬ @readme/openapi-parser@2.0.3
│   └── UNMET PEER DEPENDENCY ajv@8.10.0 
└─┬ eslint@7.7.0
  ├── ajv@6.12.4 
  └─┬ table@5.4.6
    └── ajv@6.12.4  deduped
    
    npm ERR! peer dep missing: ajv@^8.5.0, required by ajv-draft-04@1.0.0
```
so I ran `npm install ajv@8.10.0` 

Now it's fixed . Thank you!

**Comment by erunion** [comment]
Oh dang, glad you were able to solve it. Sorry for all the troubles!
