### ISSUE TITLE
Suggest similar operation IDs when using one that doesn't exist.

### ISSUE THREAD

**Issue by erunion** [readmeio/api#43]
```js
const sdk = api('petstore.json');
sdk.listPetz().then(...)
```

When calling an operation ID that doesn't exist, we currently throw an error informing the user of this but we should also suggest an alternative operation (`listPets` in this case) if their typo matches up with one that exists.

Perhaps this could throw a `TypeError` instead of a traditional `Error`.

**Comment by domharrington** [comment]
Some inspiration for this:

<img width="212" alt="image" src="https://user-images.githubusercontent.com/848223/86645231-13b5ca00-bf93-11ea-815d-7f9ba869f7b1.png">

<img width="346" alt="image" src="https://user-images.githubusercontent.com/848223/86645392-37791000-bf93-11ea-918d-00d42e06397e.png">

This module could be a good thing to use: https://www.npmjs.com/package/leven
