### ISSUE TITLE
Make time limit on api call

### ISSUE THREAD

**Issue by Oranjoose** [readmeio/api#432]
Occasionally an api call to a server will just hang indefinitely. I couldn't find in the documentation any way to supply a timeout in case the server hangs. Or am I wrong? Thank you

**Comment by erunion** [comment]
We currently don't have a way to set a timeout on requests, but we'll add one in our upcoming v5 release. Figure we can piggyback off our existing `sdk.config()` architecture with a `timeout` property there.

```js
sdk.config({ timeout: 30 });
```
