### ISSUE TITLE
x-www-form-urlencoded encoding of body when using JavaScript with Axios

### ISSUE THREAD

**Issue by j12y** [readmeio/api#436]
The code generated for JavaScript Axios when the **Content-Type** is *application/x-www-form-urlencoded* should be wrapped in a `new URLSearchParams()` call.  That is currently the case with the Fetch library, but the code generated for Axios with the JavaScript language does not include it.

Current code generated for Axios:
```
data: {grant_type: 'client_credentials'}
```

Recommended code for Axios:
```
data: new URLSearchParams({grant_type: 'client_credentials'})
```

With Fetch, the result is correct:
```
body: new URLSearchParams({grant_type: 'client_credentials'})
```

With Node + Axios, the result is correct:
```
const encodedParams = new URLSearchParams();

encodedParams.set('grant_type', 'client_credentials');

const options = {
  method: 'POST',
  ...
  headers: {
    Accept: 'application/json',
    'Cache-Control': 'no-cache',
    'Content-Type': 'application/x-www-form-urlencoded',
  },
  data: encodedParams
};
```

**Comment by erunion** [comment]
Good to know! I'll fix this in our fork of [httpsnippet](https://npm.im/httpsnippet): [@readme/httpsnippet](https://github.com/readmeio/httpsnippet)

**Comment by erunion** [comment]
@j12y https://github.com/readmeio/httpsnippet/pull/87 will fix your issue if you don't mind taking a look.
