### ISSUE TITLE
Not able to install the SDK in any project

### ISSUE THREAD

**Issue by Kanika637** [readmeio/api#489]
I made an SDK using the swagger open spec definition for my API named `@api/yaus_link_generation`, (SDK's name) the command `npm install @api/yaus_link_generation` is working fine in my personal directory in which the SDK was made.
<br>
But in a different directory, I am getting this error:

![image](https://user-images.githubusercontent.com/84350895/179240028-f24167d0-d57e-4b83-8ea7-caa4a056f0da.png)

Not able to install it in any other directory

**Comment by domharrington** [comment]
Hey! So the module right now doesn't provide a first class way to publish these generated SDKs onto npm. The preferred workflow is for your users to install it via a URL to the OAS spec like so:

```sh
npx api@beta install https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.json
```

It would be excellent if you could run `npm publish` in the generated directory, then your users could run `npm install` on it from anywhere. But this isn't what this module does at this point. Assigning this to @erunion who is in charge of this module.

**Comment by Kanika637** [comment]
Thanks @domharrington , will try `npm publish`

**Comment by Kanika637** [comment]
Well, getting this `npm ERR! code EBADSEMVER
npm ERR! invalid semver: ` by using the command `npm publish`

**Comment by domharrington** [comment]
Yeah we don't currently support running npm publish of the generated SDK at the moment. This is a feature request for future. The intended usage is installing from a URL:

```sh
npx api@beta install https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.json
```

**Comment by Kanika637** [comment]
@erunion  yes, I am just trying to use this SDK which I just created in another codebase

**Comment by erunion** [comment]
Ah ok. You'll need to either publish that SDK to NPM yourself, or re-run the SDK generation in that other codebase.

We have plans to at some point offer commands in `api` that'll help you publish the package but for now it's a very manual process for you unfortunately.

**Comment by Kanika637** [comment]
Okay @erunion , thanks for the guidance 👍
