### ISSUE TITLE
opinionated SDK for TypeScript

### ISSUE THREAD

**Issue by dominik-meissner** [readmeio/api#498]
I am trying to generate a SDK with Types from an API but even the sample code fails:

`npx api install https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.json`

-> `could not determine executable to run`

There is no `"bin"` entry in the `package.json` so i am a little confused how this could work...

Any help appreciated!

**Comment by erunion** [comment]
Hi! The CLI aspect of this package is still in an open beta channel so you'll need to do `npx api@beta install ...` to access it.
