### ISSUE TITLE
npx api returns error npx api@beta does not

### ISSUE THREAD

**Issue by mikgross** [readmeio/api#511]
In your documentation you have a reference to `npx api ....`; this results in the error `npm ERR! could not determine executable to run`.

**Comment by domharrington** [comment]
Hey! Thanks for raising this. This is expected behaviour for now, since the latest published version on npm is 4.5.2 - which is the "legacy" version. We're hoping to do a proper release of v5 (out of beta) soon.

**Comment by purge** [comment]
riiight.. so the documentation is for a version that hasn't been released yet? might be worth putting a banner somewhere about that

**Comment by erunion** [comment]
Done.
