### ISSUE TITLE
Wrong value shown in "api" example on generated ReadMe API Reference

### ISSUE THREAD

**Issue by bennycode** [readmeio/api#512]
I like the auto-generated ReadMe page which shows samples of how to use the "api" package but I noticed a small glitch: My endpoint accepts a payload with a "key" and the value for the "key" can only be "standard" or "technology". 

When I open my generated API reference, then "standard" is selected in the dropdown for being the value of "key" but the API examples list a "key" of value "key" (which is wrong). I have to actively select in the dropdown a different key in order to make the API example work.

**Screenshot:**

![image](https://user-images.githubusercontent.com/469989/184602773-10d8539f-7647-4129-9a01-0fa6b3e01d95.png)

**Comment by domharrington** [comment]
Hey! This seems like a bug in ReadMe the platform, vs the api module. Would you mind sending this through to support@readme.io so it can get picked up by the support team? 🙏
