### ISSUE TITLE
Issue with TS sdk generation: unclosed paren

### ISSUE THREAD

**Issue by dustinmichels** [readmeio/api#523]
Hello! I'm super excited about the ability to generate TS sdks from an OpenID definition.

I'm encountering an error when I run:

```sh
npx api install @journeyid/v1.0#2qy6513l3p6ue28 -l ts
```

That looks like this:

```sh
✖ Generating your SDK
Unexpected token, expected ")" (766:0)
   1 | import Oas from 'oas';
   2 | import APICore from 'api/dist/core';
   3 | import definition from './openapi.json';
   4 |
```

And indeed, something looks fishy around line 766:

```txt
   765 | type SystemExecutionsCreate_Response_2XX = (0
   766 | interface SystemPipelinesExecuteBodyParam {
   767 | pipelineKey: string
```

I have npm installed `"api": "^5.0.0-beta.3",`.

Let me know if you have any thoughts!

**Comment by erunion** [comment]
Oh, yikes. It seems that [json-schema-to-typescript](https://www.npmjs.com/package/json-schema-to-typescript) can't handle schema `title` properties that start with a number and is turning `260 Created` into `0Created`.

![Screen Shot 2022-10-03 at 5 54 46 PM](https://user-images.githubusercontent.com/33762/193711860-b7c1cf28-e4ce-4f5a-846a-2025b9b1d0de.png)

**Comment by erunion** [comment]
Ticketed upstream in https://github.com/bcherny/json-schema-to-typescript/issues/489 but I'll see if I can fix this in the JSON Schema we're generating for this in our [oas](https://npm.im/oas) library. This is a great find, @dustinmichels.

**Comment by dustinmichels** [comment]
Awesome, I'm glad you were able to reproduce!

**Comment by erunion** [comment]
@dustinmichels A fix for this is currently in `main` but I'm working on a few other things to get this ready for a proper v5 release within the next two weeks so it'll go out then. Thanks again for finding this (and sorry you found it)!

**Comment by dustinmichels** [comment]
@erunion That's amazing!! Thank you
