### ISSUE TITLE
Cannot install "api" when using Node.js v18

### ISSUE THREAD

**Issue by bennycode** [readmeio/api#524]
I am running Node.js v18 on my machine (which is the current release) but your "api" package rejects Node v18:

```
yarn add api
yarn add v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
error @readme/oas-to-har@16.1.0: The engine "node" is incompatible with this module. Expected version "^12 || ^14 || ^16". Got "18.7.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by erunion** [comment]
We support Node 18 in our v5 beta which will be out within the next two weeks. We currently have no plans to update the v4 series.

**Comment by prescottprue** [comment]
Getting an error installing in Node v18 due to `json-schema-to-ts`:

```
error json-schema-to-ts@2.6.1: The engine "node" is incompatible with this module. Expected version "^16.10.0". Got "18.12.1"
```

It appears that [json-schema-to-ts has an open issue around this where they mention a beta version with support](https://github.com/ThomasAribart/json-schema-to-ts/issues/106)

**Comment by erunion** [comment]
@prescottprue Sure. I'll tag v5.0.4 with https://github.com/readmeio/api/pull/576 shortly.

**Comment by jhreis** [comment]
I am receiving this warning again with node >= v19:
`Expected version ">=12 <18". Got "19.1.0"`

Can open another ticket if wanted. I can also suppress the warning but would obviously prefer not to do this.

**Comment by jhreis** [comment]
Thanks, posting here to close the loop
https://github.com/readmeio/api/issues/590
