### ISSUE TITLE
how do I import?

### ISSUE THREAD

**Issue by sgehrman** [readmeio/api#537]
const sdk = require('api')('@reservoirprotocol/v1.0#4vl21xl9d4zcp0');

How do I import? Why is this overly complicated without examples?

**Comment by sgehrman** [comment]
![gnome-shell-screenshot-U4G4T1](https://user-images.githubusercontent.com/287137/196317514-98fdbe6f-1149-4e18-b4ea-cde7edbd9a7d.png)

**Comment by sgehrman** [comment]
how do I get this beta?

"I actually rewrote api into TypeScript with our v5 release that's currently in the beta channel on NPM!"

no instructions..

**Comment by erunion** [comment]
I know you closed this out, but to answer your question, v4 of `api` doesn't ship any TypeScript types so you'll need to add a `declare module 'api';` line into a `typings.d.ts` file somewhere in your codebase for `api` to be importable. I've rewritten the library in TS for our upcoming v5 release, however, so you won't need to do anything special to load it there. I'm hoping to get v5 out by the end of the month.
