### ISSUE TITLE
Lockfile changing affects during deploy

### ISSUE THREAD

**Issue by HaoboZ** [readmeio/api#540]
I'm using the 1.0 version, when I deploy this to vercel, I get problems with the lockfile changing every single time and it throws errors, anyway to resolve?
Also using yarn berry if this matters.

**Comment by erunion** [comment]
You're using this version https://www.npmjs.com/package/api/v/1.0.0-0, or you ran `npx api install <some openapi definition>` and are using a codegen'd library from that?

**Comment by HaoboZ** [comment]
Yes, I am using api install for an openapi

**Comment by erunion** [comment]
That's very strange, the lockfile should only ever change the lockfile when you run `api install`. Are you running `api install` multiple times for the same OpenAPI definition, or you've just run it once and after that the lockfile changes?

**Comment by HaoboZ** [comment]
I ran it once and never again, but when I run yarn install sometimes, it will change the hash and checksum in the lockfile. It does seem to only be if I switch between windows and linux, maybe because of the line separators?

**Comment by erunion** [comment]
I wonder if this is because the installer uses `npm install` regardless if you use Yarn. Maybe if it did a `yarn install` if you have a `yarn.lock` these problems would go away.
