### ISSUE TITLE
`npx api install <openapi.json url>` does not install package to local `package.json`

### ISSUE THREAD

**Issue by george-bitdotio** [readmeio/api#561]
Hi!

I'm trying to generate an SDK and use it in a library I'm building but when I follow the installation instructions using `npx api install` and a URL to my `openapi.json`, the generated package is not added as a dependency to my local `package.json`

Steps to reproduce:
1. `mkdir api-test && cd api-test`
2. `npm init`
3. `npx api install https://api.bit.io/openapi.json -l ts`
   - select `bitdotio` as name for generated SDK
   - confirm package installs
4. installation completes without error and the files are generated in `.api`, but `package.json`, `package-lock.json` and `node_modules` are unaltered. I am unable to import `@api/bitdotio`.

I'm using npm 8.5.5 and node 16.14.2

Hopefully I'm missing something obvious here 😅

**Comment by erunion** [comment]
I'm able to replicate what you're seeing. Looking into it! 😬

**Comment by erunion** [comment]
This is now resolved with v5.0.2. Sorry about that! 🙃

![Screen Shot 2022-11-24 at 9 25 53 PM](https://user-images.githubusercontent.com/33762/203907222-3a54414f-fe98-4103-934f-99e756f25fbd.png)

**Comment by george-bitdotio** [comment]
Works now! Thanks for the quick fix :~)
