### ISSUE TITLE
CJS/JS intellisense suggestions doesn't align with actual types

### ISSUE THREAD

**Issue by kanadgupta** [readmeio/api#588]
Node version: v16.14.0
npm version: 8.3.1

1. Create a new directory, run `npm init -y`
2. Install and set up using our spec, then select JS + CJS options in prompts:

```sh
npx api@latest install @developers/v2.0#452hs23laswqxqy
```

2. Create a new file called `index.js`, note that when you bring up intellisense[^1] when importing the package, it suggests using `.default`:

<img width="855" alt="CleanShot 2022-12-06 at 09 59 34@2x" src="https://user-images.githubusercontent.com/8854718/205961280-f095fc4f-223b-4b26-98b3-9c6327b2ff2f.png">

And if you keep using intellisense, you'll notice that `readme.default.` starts suggesting functions:

<img width="909" alt="CleanShot 2022-12-06 at 10 01 06@2x" src="https://user-images.githubusercontent.com/8854718/205961932-d0087b91-377e-4be8-ad24-d174805387d5.png">

If you continue using intellisense to populate a function and then attempt to run it, you'll run into a `TypeError`:

<img width="647" alt="CleanShot 2022-12-06 at 10 04 06@2x" src="https://user-images.githubusercontent.com/8854718/205962127-e856be8c-cf80-44d9-8b60-8376c3228ba9.png">

The fix here is to remove the `.default` and it works as expected, but then Intellisense isn't nearly as helpful unless you know the exact method to use. Here's a full demo of the behavior:

https://user-images.githubusercontent.com/8854718/205963131-c6108585-37af-4670-b909-2eade8666abd.mp4

[^1]: <kbd>ctrl</kbd> + <kbd>space</kbd> for me, and also for [most keyboard shortcut configurations](https://code.visualstudio.com/docs/editor/intellisense#:~:text=You%20can%20trigger%20IntelliSense%20in,(.)%20in%20JavaScript).

**Comment by erunion** [comment]
Christ, this is going to be hard to fix. The way to get the default export to be the SDK is to have the `index.d.ts` file be `export = createSDK` but that doesn't work because we export types there.

![Screen Shot 2022-12-06 at 1 09 45 PM](https://user-images.githubusercontent.com/33762/206023649-7a5f801c-ab06-4ad9-ad40-1d69ced16062.png)

Maybe if we're exporting JS code we don't export types from the main entrypoint?

**Comment by kanadgupta** [comment]
Those types are exported for the user’s convenience, right? Nothing else? If so then yeah I can’t imagine anyone using those in JS projects

**Comment by erunion** [comment]
yeah if you're using JS you can't use them anyways i guess
