### ISSUE TITLE
SDK not working in browsers

### ISSUE THREAD

**Issue by tzelon-cypator** [readmeio/api#595]
Hey, 
In the FAQ it says 
"If you generate an SDK with the CLI installation process then yes! If you're having trouble getting autogenerated SDKs working in a browser"

I use `npx api install ***` to install my sdk, but when I try to use it I get `Module not found: Can't resolve 'fs/promises'`
I see that the generated code imports `/api/dist/core` which import the `prepareParams.ts`, and that file imports nodejs modules. 

Thank you, for your help.

**Comment by erunion** [comment]
I'll update that guide as it's not completely accurate but in a browser environment you will need to polyfill `fs` as we load `fs` in `prepareParams.ts` in order to handle file uploads within SDKs with something like Webpack.

I believe if you add this to your `package.json` then Webpack will pick it up and make it ok:

``
"browser": {
  "fs": false
},
```

Let me know if that works and I'll update the guide to mention this.

**Comment by bkniffler** [comment]
This doesn’t work, because you’re importing `fs/promise`, which popular polyfill plugins like esbuild node polyfill does not recognize. Could you switch to using `fs` instead of `fs/promise`?

**Comment by bkniffler** [comment]
Or, maybe, if you could simply make sure to have a pure browser compatible build that you allow to use via package.json `browser` field, that would help. I’ve not been able to get this to work. This is not only for browser environment, but cloudflare workers will also not work with the api package.

**Comment by erunion** [comment]
Alright I've got a PR here[^1] to move from `fs/promises` to `fs` in our client-side code. Hopefully this fixes the problem otherwise I'll look into adding a `browser` field to the `package.json` file(s).

[^1]: https://github.com/readmeio/api/pull/605

**Comment by bkniffler** [comment]
Thanks, appreciate the effort. Very eager to use the api package with some readmeio libraries (including our own that we host on readme) on cloudflare workers.

**Comment by erunion** [comment]
I've just published v5.0.7 which changes our `fs/promises` usage in that core library to `fs`. Hopefully that resolves your issues.

**Comment by erunion** [comment]
@JPCanaverde There's some discussion about that in #604 but I haven't had a chance in a while to dig into how to resolve it.

**Comment by JPCanaverde** [comment]
@erunion thanks 🙂 I managed to find a [workaround](https://github.com/readmeio/api/issues/604#issuecomment-1533950156).
