### ISSUE TITLE
SDK generated by cli has incorrect return types

### ISSUE THREAD

**Issue by GravlLift** [readmeio/api#612]
When generating an SDK via `npx api install <doc>`, the generated client will contain functions with return types composed of a union of all of the possible responses from a given API. For instance, take this one function generated by `npx api install @samsara-dev-rel/v2019.01.01#20op2bldf7yj03 -l ts`.

```ts
  createRoute(
    body: types.CreateRouteBodyParam
  ): Promise<
    | FetchResponse<200, types.CreateRouteResponse200>
    | FetchResponse<401, types.CreateRouteResponse401>
    | FetchResponse<404, types.CreateRouteResponse404>
    | FetchResponse<405, types.CreateRouteResponse405>
    | FetchResponse<429, types.CreateRouteResponse429>
    | FetchResponse<500, types.CreateRouteResponse500>
    | FetchResponse<501, types.CreateRouteResponse501>
    | FetchResponse<502, types.CreateRouteResponse502>
    | FetchResponse<503, types.CreateRouteResponse503>
    | FetchResponse<504, types.CreateRouteResponse504>
    | FetchResponse<number, types.CreateRouteResponseDefault>
  > {
    return this.core.fetch("/fleet/routes", "post", body)
  }
```

Of those, however, only `FetchResponse<200, types.CreateRouteResponse200>` is an actual possible return value. [As per the documentation, all of the response types from 400-599 will instead throw a FetchError](https://github.com/readmeio/api/blob/main/docs/making-requests.md#error-handling), and thus will never be returned by the function call.

The generated method should look more like this:

```ts
  createRoute(
    body: types.CreateRouteBodyParam
  ): Promise<
    | FetchResponse<200, types.CreateRouteResponse200>
    | FetchResponse<number, types.CreateRouteResponseDefault>
  > {
    return this.core.fetch("/fleet/routes", "post", body)
  }
```

**Comment by erunion** [comment]
Ah thanks for this, I hadn't thought that folks might be documenting responses of 400+ errors. I'll update SDK generation to filter these out from being added during codegen.

**Comment by calvin-sketchsoft** [comment]
Hi all,
I've just faced this issue while implementing `@revenuecat/v5.1#3bui71ulibgsx0t` with `api` to our team's project.
```ts
// index.ts
  /**
   * Gets the latest subscriber info or creates one if it doesn't exist.
   *
   * @summary Get or Create Subscriber
   */
  subscribers(
    metadata: types.SubscribersMetadataParam,
  ): Promise<
    | FetchResponse<200, types.SubscribersResponse200>
  | FetchResponse<400, types.SubscribersResponse400>
  | FetchResponse<401, types.SubscribersResponse401>
  > {
    return this.core.fetch('/subscribers/{app_user_id}', 'get', metadata);
  }
```
```ts
const data = await SDK.subscribers({ app_user_id: 'userId' })
  .then(({ data }) => data); // data: unknown;
```
Since its result can be any of 3, VS Code Intellisense just gives up and spits out `unknown` to result.data.
I can comment out `400` and `401` FetchResponses and settle for now, but I just wanted to raise this issue's importance: it breaks a lot, if not all, of reasons to choose codegen over dynamic.
