### ISSUE TITLE
Question: Should you git ignore .api folder?

### ISSUE THREAD

**Issue by Cmoen11** [readmeio/api#614]
It's a pretty big folder, and I'll take up some space in the git repo, I'd like to know if this folder is generated by yarn install/npm install.

if not, I can add it in the git ignore.

Thanks!

**Comment by erunion** [comment]
You can ignore the `node_modules/` directory in it, but it's generally recommended to not ignore `.api/` on a whole as if you use an SDK within it you'll need to regenerate that SDK as part of your build + deployment process (like you would with a Webpack dist).
