### ISSUE TITLE
Next.js Edge Runtime

### ISSUE THREAD

**Issue by siacomuzzi** [readmeio/api#695]
Hi,

I wonder if there is any recommendation on how to port this library to be used with Next.js Edge Runtime. I tried today and I got a few "module not found" errors:

```
Server Error
Error: Module not found: Can't resolve 'http'
Did you mean './http'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories
...
```

Thank you

**Comment by erunion** [comment]
I unfortunately have no experience with Next's Edge Runtime but I'm guessing that they don't support loading core Node modules, like `http`, in executed code.

**Comment by kanadgupta** [comment]
@erunion if we eventually drop Node 16 support we could also drop `isomorphic-fetch` and solely rely on the `fetch` global?

**Comment by erunion** [comment]
@kanadgupta We should be able to do that yea

**Comment by kanadgupta** [comment]
for posterity, this issue comment has a good solution for Node 18 `fetch` types: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/60924#issuecomment-1707342243

**Comment by kanadgupta** [comment]
For additional posterity: https://nextjs.org/docs/app/api-reference/edge

**Comment by erunion** [comment]
We've completely moved over to native `fetch` in the coming v7 work so this should now be resolved there.
