### ISSUE TITLE
Library does not support circular references in OAS

### ISSUE THREAD

**Issue by bennycode** [readmeio/api#700]
I just tried to generate an API client for [Alpaca](https://docs.alpaca.markets/reference/) using the following command:

```bash
npx api install https://dash.readme.com/api/v1/api-registry/zryj16ll4d1dl0
```

Unfortunately, it failed with the following response:

> Generating your SDKC: node_modules\api\dist\cli\codegen\language.js:24
> throw new Error('Sorry, this library does not yet support generating an SDK for an OpenAPI definition that contains circular references.');

**Comment by erunion** [comment]
Yeah this is unfortunately an issue now with how we handle `$ref` parsing. https://github.com/readmeio/api/issues/549
