### ISSUE TITLE
dependency @readme/api-core

### ISSUE THREAD

**Issue by phuhh98** [readmeio/api#749]
Version ^7.0.0-alpha.1
Would the generated api sdk include @readme/api-core in output package.json?
I see that generated api in index.js will required this module, but the generated package.json does not and I had to manually install this package from base project.

Version 7.0.0-alpha.3: 
at @readme\api-core\dist\index.js:68:50, when invoke api call get error
Error while calling <api name> TypeError: (0 , import_remove_undefined_objects.default) is not a function
it seems that has some reference error while import  @readme\oas-to-har\dist\index.cjs:605:69.

**Comment by kanadgupta** [comment]
Hi, v7 is currently in an unstable alpha and still heavily under development. Please stick with `api@6` until `api@7` is published to the `latest` channel.
