### ISSUE TITLE
api install is erasing previous definition

### ISSUE THREAD

**Issue by valas69** [readmeio/api#812]
I have multiples open api specifications
- @developers/v2.0#uid1
- @developers/v2.0#uid2

When I am installing them, for example uid1 then uid2, uid2 erase uid1's specifications so I cannot use it
How to prevent this ?

**Comment by TateParker** [comment]
> installing with direct link rather than using identifier ask me package identifier

Where did you get the direct links? All I can find in the documentation provided is the identifier(s) and I'm having the same issue.

**Comment by ThallesP** [comment]
> installing with direct link rather than using identifier ask me package identifier

what the hell is a direct link
