### ISSUE TITLE
Error with returning sdk instance

### ISSUE THREAD

**Issue by dmitriy-MI6** [readmeio/api#813]
1. Version api: 6.1.0
2. Node.js: 18

I have multiple API keys that are responsible as load-balancing, so we are not blocked from 3rd party API.
`
public getClient(key: string) {
const s = sdk('@leonardoai/v1.0#28807z41owlgnis8jg');
    s.auth(key);
    return s;
}
`
When I try to return sdk instance with a new key I return the next error:
![image](https://github.com/readmeio/api/assets/28542856/94993caa-f4a2-4c03-93b5-f5cd6451634d)

But if I do in the next way, everything works good.
`
this.sdk = sdk('@leonardoai/v1.0#28807z41owlgnis8jg');
    this.sdk.auth(key);
`

How to fix it?

**Comment by erunion** [comment]
Can you paste a full snippet that's failing? How are you calling `getClient()`? The error that's being thrown is because I believe you're trying to do `getClient().then()` somewhere and `then` isn't a valid operationID in the API definition you're using.

**Comment by dmitriy-MI6** [comment]
@erunion
```
import * as sdk from 'api';

public async createClient() {
    const key = await this.generateKey();
    const s = sdk('@leonardoai/v1.0#28807z41owlgnis8jg');
    s.auth(key);
    return s;
  }
```
Here is how I call that function:
```
const client = await this.createClient();
const response = await client.createGeneration({ prompt: query });
```

**Comment by erunion** [comment]
The [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) work that we have in v6 of `api` seems to be misinterpreting being _returned_ as a Promise in your `createClient` method. I was able to replicate the same with this smaller snippet:

```js
import sdk from 'api';

async function createClient() {
  const s = sdk('@leonardoai/v1.0#28807z41owlgnis8jg');
  return s;
}

const client = await createClient();
const response = await client.createGeneration({ prompt: 'query query example' });

console.log(response)
```

Whereas extracting client creation out works:

```js
import sdk from 'api';

const client = sdk('@leonardoai/v1.0#28807z41owlgnis8jg');
const response = await client.createGeneration({ prompt: 'query example' });
```

The unfortunatley thing is that in the upcoming v7 release of this library we've removed this `sdk('@leonardoai/v1.0#28807z41owlgnis8jg');` method of instantiating an SDK infavor of requiring folks to invoke our code generation tool.

If you'd like to try it out you can run this command to generate a ready-to-go SDK for this API:

```shell
npx api@next install @leonardoai/v1.0#28807z41owlgnis8jg
```

This codegen work also exists in v6 of `api` but we've made a lot of improvements to it in the `next` channel to work in CJS and ESM environments so I'd recommend trying that out.

**Comment by dmitriy-MI6** [comment]
Where is 'auth' method call in your code?

**Comment by dmitriy-MI6** [comment]
![image](https://github.com/readmeio/api/assets/28542856/35b154b0-9387-4539-ab94-b03eb4261076)
And downloading from api@next doesn't make any progress.

**Comment by dmitriy-MI6** [comment]
I decided to go with my own solution.
Unfortunately, such a little problem gives a lot of problems and waste of time.

**Comment by kanadgupta** [comment]
@dmitriy-MI6 apologies for the problems you're running into! I wasn't seeing that issue with the CLI hanging on my end, could it have been a temporary hiccup with your internet connection? What version of `npm` do you have installed? You can find this by running `npm --version`.

While I was able to run the installer successfully, it errored out while attempting to compile the SDK due to issues with the API definition. It's on our roadmap to make these errors more digestible!

![CleanShot 2023-11-08 at 10 52 12@2x](https://github.com/readmeio/api/assets/8854718/a026a73f-07ba-4db4-8aeb-adbbf4d25f48)
