### ISSUE TITLE
SDK Prepare Server Selection Issue

### ISSUE THREAD

**Issue by akramali86** [readmeio/api#822]
If a server is index 0 in the `servers` array in the generated `openapi.json` it is incorrectly ignored due to it being falsy. I think the issue is this [line](https://github.com/readmeio/api/blob/ef4982182e9abc40d6e75b655db2e776e1018352/packages/core/src/lib/prepareServer.ts#L28)

I've managed to find a work around for now, by manually adding the same server item to the `servers` array therefore it being index 1.

**Comment by bstime-tol** [comment]
This doesn't appear to have been back-ported to the stable/v6 lineage but v7 is still in beta.
