### ISSUE TITLE
Use latest stable version of json-schema-to-ts

### ISSUE THREAD

**Issue by lifeiscontent** [readmeio/api#845]
currently using `api` to create a new project adds `^2.8.0-beta.0` to the package.json

but there is a stable [3.0.0](https://github.com/ThomasAribart/json-schema-to-ts/releases/tag/v3.0.0) release

**Comment by erunion** [comment]
We're using the 3.0 release in our `next` release channel. I don't have an answer for when that'll be released but we're working on it! 😅
