### ISSUE TITLE
no way to pass Cache-Control header in get requests that don't explicitly define it

### ISSUE THREAD

**Issue by lifeiscontent** [readmeio/api#846]
I wanted to set `"Cache-Control": "s-maxage=3600, stale-while-revalidate"` but it seems I can't because the openapi spec I'm generating a client from doesn't define it in their spec, this seems like a bug, I'd doubt you should expect to define every single header which is fairly standard in a openapi spec

am I missing something here?

**Comment by erunion** [comment]
Yeah `api` is pretty opinionated at the moment and does not offer a way to send headers that aren't defined in the OpenAPI definition you're using. We've been thinking about ways on how to cleanly handle this but have yet to nail down something we're happy with.

**Comment by ChuckJonas** [comment]
This is a dealbreaker... The majority of API spec don't take the time to publish all the possible headers for every endpoint.

Why not just have optional `fetch` options parameter available on every endpoint?
