### ISSUE TITLE
api.readme.dev doesn't show the docs

### ISSUE THREAD

**Issue by tobiase** [readmeio/api#866]
That is what I see instead. Additionally links to specific doc pages show a 404.
![image](https://github.com/readmeio/api/assets/487379/95e4b7a4-c349-4b89-8383-d915f4cc0828)

**Comment by erunion** [comment]
thanks for the heads up. there was a dns change on that domain for a talk last week and it didn't get rolled back afterwards, this'll be resolved later today.
