### ISSUE TITLE
7.0.0 Unexpected identifier 'assert' with Node 22

### ISSUE THREAD

**Issue by marklai1998** [readmeio/api#950]
Node 22 is LTS now, and import assertion is removed favor of input attributes

So when I run the command with 7.0.0, error is thrown

`SyntaxError: Unexpected identifier 'assert'`

**Comment by kanadgupta** [comment]
Hi there — [`v7.0.0-beta.11`](https://github.com/readmeio/api/releases/tag/v7.0.0-beta.11) should fix this. Thanks for flagging!
